config/routes.rb
Rails.application.routes.draw do

		get 'index' => 'tamilnadu_polls#index', as: 'tamilnadu_polls_index'
		post 'create' => 'tamilnadu_polls#create', as: 'tamilnadu_polls_submit'
		get 'deadline' => 'tamilnadu_polls#deadline'
		get 'chart' => 'tamilnadu_polls#chart', as: 'tamilnadu_polls_chart'
		root to:"tamilnadu_polls#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deadline.rb
# == Schema Information
#
# Table name: deadlines
#
#  id         :integer          not null, primary key
#  endtime    :datetime
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Deadline < ApplicationRecord
end

app/models/tamilnadu_poll.rb
# == Schema Information
#
# Table name: tamilnadu_polls
#
#  id         :integer          not null, primary key
#  ip         :string
#  email      :string
#  choice     :integer
#  voter      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TamilnaduPoll < ApplicationRecord

	enum choice: [:aiadmk,:rajini,:kamal,:dmk,:pmk,:dmdk,:other,:bjp,:congress]
	enum voter: [:adult,:child]

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255},format: {with: VALID_EMAIL_REGEX},uniqueness: {case_sensitive: false}
	before_save :email_downcase 
	validate :ip_used_three_times?


	private
	def email_downcase
  	self.email.downcase!
	end

	def ip_used_three_times?
		a = TamilnaduPoll.where(ip: self.ip)
		if a.count == 4 then
			self.errors.add(:ip, "used more than three times.!")
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tamilnadu_polls_controller.rb
class TamilnaduPollsController < ApplicationController

	def index
		@tamilnadu_poll = TamilnaduPoll.new
	end

	def create
		@tamilnadu_poll = TamilnaduPoll.new(create_params)
		ip = request.env['REMOTE_ADDR']
		@tamilnadu_poll.update(ip: ip)

		if @tamilnadu_poll.save
			flash[:success] = "Response Successfully recorded!"
			redirect_to(tamilnadu_polls_chart_path)
		else
			flash[:danger] = @tamilnadu_poll.errors.full_messages
			redirect_to(tamilnadu_polls_index_path)
		end
	end

	def deadline
		deadline = Deadline.find(1).endtime
		render json:{deadline: deadline}
	end

	def chart
	end

	private 
	def create_params
		params.require(:tamilnadu_poll).permit(:choice,:email,:voter)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tamilnadu_polls_helper.rb
module TamilnaduPollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TamilNadu Virtual Elections- Qperweek</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'qplogo.png', rel: 'shortcut icon', type: 'image/png'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <script type="text/javascript" src="http://cdn.rawgit.com/hilios/jQuery.countdown/2.1.0/dist/jquery.countdown.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Concert+One|Ruda" rel="stylesheet">
  </head>
  <body>
    <div class = "header">
      <div class = "title class-md-12">
        <%= link_to root_path do%> <%= image_tag("logo.png", class:"img-responsive")%><% end %>
      </div>
      <div class = "sub-title class-md-12">
        <i>"Know answers to the unknown..! Voice your opinion..!"</i>
        <div class = "share">
        <a href="whatsapp://send?text=Tamilnadu Virtual Elections..! Check it out ! http://qperweek.herokuapp.com" data-action="share/whatsapp/share"><%= image_tag("whatsapp.png", class:"share-logo")%></a>
        <iframe src="https://www.facebook.com/plugins/share_button.php?href=http%3A%2F%2Fqperweek.herokuapp.com&layout=button&size=small&mobile_iframe=true&width=59&height=20&appId" width="59" height="20" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
        <a onclick="window.open('https://twitter.com/intent/tweet?text=Tamilnadu Virtual Elections..! Check it out ! http://qperweek.herokuapp.com', 'newwindow', 'width=700, height=700'); return false;">
        <%= image_tag("twitter.png", class:"share-logo")%></a>
      </div>  
      </div>
    </div>
    <%= yield %>
    <%= link_to tamilnadu_polls_chart_path do%><span class="label label-success">Results-Click here!</span><%end%>
    <div class = "footer copyright">
      <p>&copy; All rights reserved. Qperweek-2017.</p> 
    </div>
  </body>
</html>

app/views/tamilnadu_polls/chart.html.erb
<% if flash[:success].present? %>
		<div class="alert alert-success alert-dismissable fade in">
			<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
			<%= flash[:success]%>
		</div>
	<% end %>
<div class = "chart-container ">
	<div class = "count"><p>Total no of Votes: <%=TamilnaduPoll.all.count%></p></div>
	<div id = "no-of-votes" class = "col-md-6 col-sm-6 col-xs-12 well"><span class="label label-primary">No of Voters above and below 18</span><%= column_chart TamilnaduPoll.group(:voter).count %></div>
	<div id = "vote_distribution" class = "col-md-6 col-sm-6 col-xs-12 well" ><span class="label label-primary">Vote distribution</span><%= pie_chart TamilnaduPoll.group(:choice).count %></div>
</div>

app/views/tamilnadu_polls/index.html.erb
<div class = "container main-div">
	<% if flash[:success].present? %>
		<div class="alert alert-success alert-dismissable fade in">
			<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
			<%= flash[:success]%>
		</div>
	<% end %>

	<% if flash[:danger].present? %>
		<div class="alert alert-danger alert-dismissable fade in">
			<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
			<% unless flash[:danger].kind_of?(Array) %>
				<%= flash[:danger]%>
			<% else %>
				<% flash[:danger].each do |error| %>
					<%=error %><br/>
				<% end %>			
			<% end %>
		</div>
	<% end %>
	<div class = "col-md-6 left-div">
		<div class = "timer" id="countdown"></div>
	</div>
	<div class = "col-md-6 right-div">
		<%=form_for :tamilnadu_poll, url: tamilnadu_polls_submit_path do |f| %>
			<div class = "question-space">
				<p> Who would you vote for in the upcoming election? </p>
			</div>
			<div class = "options-space">
				<div class="options col-md-6 col-xs-6">
					<div class = "option">
					<label for="kamal">
						<%= f.radio_button :choice, 'kamal', class:"radio" , id: 'kamal',checked: true%>
						 KamalHassan</label>
					 </div>
					<div class = "option">
						<label for="rajini">
						<%= f.radio_button :choice, 'rajini', class:"radio",id: 'rajini'%>
						 RajiniKanth</label>
					 </div>
				</div>
				<div class="options col-md-6 col-xs-6">
					<div class = "option">			
						<label for="aiadmk">
						<%= f.radio_button :choice, 'aiadmk', class:"radio" , id: 'aiadmk'%>
						 AIADMK</label>
					 </div>
					<div class = "option">			
						<label for="dmk">
						<%= f.radio_button :choice, 'dmk', class:"radio",id: 'dmk'%>
						 DMK</label>
					 </div>
				</div>
				<div class="options col-md-6 col-xs-6">
					<div class = "option">			
						<label for="pmk">
						<%= f.radio_button :choice, 'pmk', class:"radio" , id: 'pmk'%>
						 PMK</label>
					 </div>
					<div class = "option">			
						<label for="dmdk">
						<%= f.radio_button :choice, 'dmdk', class:"radio",id: 'dmdk'%>
						 DMDK</label>
					 </div>
				</div>
				<div class="options col-md-6 col-xs-6">
					<div class = "option">			
						<label for="bjp">
						<%= f.radio_button :choice, 'bjp', class:"radio" , id: 'bjp'%>
						 BJP</label>
					 </div>
					<div class = "option">			
						<label for="congress">
						<%= f.radio_button :choice, 'congress', class:"radio",id: 'congress'%>
						 Congress</label>
					 </div>
				</div>
				<div class="options col-md-12 col-xs-6">
					<div class = "option">			
						<label for="other">
						<%= f.radio_button :choice, 'other', class:"radio" , id: 'other'%>
						 Others</label>
					 </div>
					
				</div>
			</div>
			<div class = "submit-section">
				<div class="form-group">
					<%=f.email_field :email, class:"form-control",placeholder: "Email (required)" , required: true%>
				</div>
				<div><span class = "text-field">Click the button below if you are 18 or above!</span></div>
				<label class="switch">
					<%= f.check_box :voter, {class: ""}, "adult", "child" %>
					<span class="slider round"></span>		
				</label>
				<div class = "submit-button">
					<%= button_tag(type: 'submit', class: "btn btn-success submit-button", style: "font-family: 'Ruda', serif; font-size: 20px;" , required: true) do %>
						<span class="glyphicon glyphicon glyphicon-ok">&nbsp;Save</span>
					<% end %>
				</div>
			</div>
		<%end%>
	</div>
</div>